version: "3.6"

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
    restart: always
  
  php-apache-server:
    build: php/dockerfile
    container_name: php-apache-server
    volumes:
      - ./php/src:/var/www/html/
    depends_on:
      - db
      - reverse-proxy

  nginx-server:
    image: nginx
    container_name: nginx-server
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - reverse-proxy