version: "3.6"

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  
  php:
    build: ./php/dockerfile
    container_name: php-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8081:80
    depends_on:
      - db